name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-repo-dependency]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
