name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-repo-dependency]
jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/ivona13/go-proj
      GH_ACCESS_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          #token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          #ref: ${{ github.event.client_payload.ref }}

      - name: Get version from wrapper
        run: echo ${{ github.event.client_payload.ref }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - run: go build

      - name: Install package with the new version
        run: |
          go get -t -u github.com/ivona13/go-proj@${{ github.event.client_payload.ref }}
          go mod tidy

      - name: Update go-proj version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update go-proj version to ${{ github.event.client_payload.ref }}"
