name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-repo-dependency]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/ivona13/go-proj
      GH_ACCESS_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          #token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          #ref: ${{ github.event.client_payload.ref }}

      - name: Get version from wrapper
        run: echo ${{ github.event.client_payload.ref }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - run: go build

      - name: Install package
        run: |
          go get -t -u github.com/ivona13/go-proj@${{ github.event.client_payload.ref  }}
          go mod edit -replace "github.com/ivona13/go-proj=github.com/ivona13/go-proj@"${{ github.event.client_payload.ref  }}
          #go get github.com/ivona13/go-proj@${{ github.event.client_payload.ref  }}
          go mod tidy

      - name: Git status
        run: git status

      - name: Git add
        run: git add .

      - name: Git commit
        run: git commit -m "Update version"

      - name: Git push
        run: git push origin  master
